#!/usr/bin/env python3
"""Full kill-rate evaluation for L1 + L2 kernels.

Only tests kernels that PASS correctness check and selects the iteration
with the highest speedup (from best_kernels.json generated by scan_best_kernels.py).

P1 (load_inline name patch) applied.
Tolerance aligned to KernelBench native (atol=1e-2, rtol=1e-2).
No enhanced inputs — standard get_inputs() only.
Results saved incrementally to JSON for crash recovery.
"""
import importlib.util
import json
import os
import random
import re
import signal
import sys
import tempfile
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

import torch

from src.mutengine.operators.arithmetic import ArithReplace, RelOpReplace, ConstPerturb
from src.mutengine.operators.gpu_parallel import (
    IndexReplace, SyncRemove, MaskBoundary, LaunchConfigMutate,
)
from src.mutengine.operators.ml_semantic import (
    StabRemove, AccDowngrade, EpsilonModify, ScaleModify,
    CastRemove, ReductionReorder, InitModify,
)
from src.mutengine.operators.llm_pattern import BroadcastUnsafe, LayoutAssume

KB_ROOT = Path("/home/kbuser/projects/KernelBench-0")
PROBLEM_DIRS = {
    "L1": KB_ROOT / "KernelBench" / "level1",
    "L2": KB_ROOT / "KernelBench" / "level2",
}

BEST_KERNELS_FILE = PROJECT_ROOT / "best_kernels.json"
ATOL, RTOL = 1e-2, 1e-2
NUM_TRIALS = 3
DEVICE = "cuda"
MUTANT_TIMEOUT = 180
SEED = 42
SAMPLE_PER_OP = 1

RESULT_FILE = PROJECT_ROOT / "kill_rate_full_results.json"
OUTPUT_FILE = PROJECT_ROOT / "kill_rate_full_output.txt"

ALL_OPS = [
    ("A1", ArithReplace()),
    ("A2", RelOpReplace()),
    ("A3", ConstPerturb()),
    ("B1", IndexReplace()),
    ("B2", SyncRemove()),
    ("B3", MaskBoundary()),
    ("B4", LaunchConfigMutate()),
    ("C1", StabRemove()),
    ("C2", AccDowngrade()),
    ("C3", EpsilonModify()),
    ("C4", ScaleModify()),
    ("C5", CastRemove()),
    ("C6", ReductionReorder()),
    ("C7", InitModify()),
    ("D1", BroadcastUnsafe()),
    ("D2", LayoutAssume()),
]

_LOAD_INLINE_NAME_RE = re.compile(
    r"""(load_inline\s*\([^)]*?name\s*=\s*)(['"])([^'"]+)\2""",
    re.DOTALL,
)


def _patch_load_inline_names(source, unique_suffix):
    def _repl(m):
        prefix, quote, name = m.group(1), m.group(2), m.group(3)
        return f"{prefix}{quote}{name}_{unique_suffix}{quote}"
    return _LOAD_INLINE_NAME_RE.sub(_repl, source)


class MutantTimeout(Exception):
    pass


def _alarm_handler(signum, frame):
    raise MutantTimeout()


def _timeout_kill(pid):
    """Kill a process after timeout (used as threading.Timer target)."""
    import os as _os
    try:
        _os.kill(pid, signal.SIGKILL)
    except ProcessLookupError:
        pass


def P(msg):
    print(msg, flush=True)
    with open(OUTPUT_FILE, "a") as f:
        f.write(msg + "\n")


def find_problem_file(problem_dir, problem_id):
    for f in problem_dir.iterdir():
        if f.name.startswith(f"{problem_id}_") and f.suffix == ".py":
            return f
    return None


def load_module(filepath, name):
    spec = importlib.util.spec_from_file_location(name, str(filepath))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def load_module_from_source(source, name, tmp_dir):
    source = _patch_load_inline_names(source, name)
    fp = os.path.join(tmp_dir, f"{name}.py")
    with open(fp, "w") as f:
        f.write(source)
    return load_module(fp, name)


def compare(ref, mut):
    if isinstance(ref, torch.Tensor) and isinstance(mut, torch.Tensor):
        if ref.shape != mut.shape:
            return False
        return torch.allclose(ref.float().cpu(), mut.float().cpu(), atol=ATOL, rtol=RTOL)
    if isinstance(ref, (tuple, list)) and isinstance(mut, (tuple, list)):
        return len(ref) == len(mut) and all(compare(r, m) for r, m in zip(ref, mut))
    return ref == mut


def classify(source, mutated, ref_mod, get_inputs, get_init_inputs, tmp_dir, mut_id):
    if mutated.strip() == source.strip():
        return "equivalent"

    try:
        mut_mod = load_module_from_source(mutated, f"mut_{mut_id}", tmp_dir)
    except Exception:
        return "stillborn"

    try:
        MutCls = getattr(mut_mod, "ModelNew", None) or getattr(mut_mod, "Model")
        init_args = get_init_inputs()
        mut_model = MutCls(*init_args) if isinstance(init_args, (list, tuple)) else MutCls()
    except Exception:
        return "stillborn"

    try:
        RefCls = ref_mod.Model
        init_args = get_init_inputs()
        ref_model = RefCls(*init_args) if isinstance(init_args, (list, tuple)) else RefCls()
    except Exception:
        return "stillborn"

    try:
        for trial in range(NUM_TRIALS):
            torch.manual_seed(SEED + trial)
            try:
                inputs = get_inputs()
                ref_d = ref_model.to(DEVICE).eval()
                moved_r = [x.to(DEVICE) if isinstance(x, torch.Tensor) else x for x in inputs]
                with torch.no_grad():
                    ref_out = ref_d(*moved_r)

                torch.manual_seed(SEED + trial)
                inputs2 = get_inputs()
                mut_d = mut_model.to(DEVICE).eval()
                moved_m = [x.to(DEVICE) if isinstance(x, torch.Tensor) else x for x in inputs2]
                with torch.no_grad():
                    mut_out = mut_d(*moved_m)

                if not compare(ref_out, mut_out):
                    return "killed"
            except Exception:
                return "killed"

        return "survived"
    finally:
        del mut_model, ref_model
        torch.cuda.empty_cache()
        import gc; gc.collect()


def load_existing_results():
    if RESULT_FILE.exists():
        with open(RESULT_FILE) as f:
            return json.load(f)
    return {"kernels": {}, "summary": {}}


def save_results(results):
    with open(RESULT_FILE, "w") as f:
        json.dump(results, f, indent=2)


def main():
    random.seed(SEED)

    if OUTPUT_FILE.exists():
        OUTPUT_FILE.unlink()

    # Load pre-scanned best kernels (correct + highest speedup per problem)
    if not BEST_KERNELS_FILE.exists():
        print(f"ERROR: {BEST_KERNELS_FILE} not found. Run scan_best_kernels.py first.")
        sys.exit(1)
    with open(BEST_KERNELS_FILE) as f:
        best_kernels = json.load(f)

    P(f"{'='*70}")
    P(f"  MutaKernel Full Kill-Rate Test (L1 + L2)")
    P(f"{'='*70}")
    P(f"  GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'N/A'}")
    P(f"  Tolerance: atol={ATOL}, rtol={RTOL}")
    P(f"  Timeout: {MUTANT_TIMEOUT}s per mutant")
    P(f"  Sample: {SAMPLE_PER_OP} mutant per operator per kernel")
    P(f"  Kernel selection: best correct iteration (highest speedup)")
    P(f"  Fixes: P1(load_inline patch), tol=KernelBench native(1e-2), NO enhanced inputs")
    P("")

    tmp_dir = tempfile.mkdtemp(prefix="mutakill_full_")
    results = load_existing_results()
    statuses = ["killed", "survived", "stillborn", "equivalent", "timeout"]
    total_time_start = time.time()

    # Build ordered kernel list from best_kernels.json
    all_kernels = []
    for key in sorted(best_kernels.keys()):
        info = best_kernels[key]
        level = info["level"]
        problem_id = info["problem_id"]
        kernel_path = Path(info["kernel_path"])
        speedup = info["speedup"]
        turn = info["turn"]
        problem_dir = PROBLEM_DIRS.get(level)
        if problem_dir is None:
            continue
        all_kernels.append((level, kernel_path, problem_id, problem_dir, speedup, turn))

    n_l1 = sum(1 for k in all_kernels if k[0] == "L1")
    n_l2 = sum(1 for k in all_kernels if k[0] == "L2")
    P(f"  Correct kernels to test: {len(all_kernels)} (L1={n_l1}, L2={n_l2})")
    P("")

    grand = {s: 0 for s in statuses}
    cat_grand = {c: {s: 0 for s in statuses} for c in "ABCD"}
    level_grand = {lv: {s: 0 for s in statuses} for lv in ["L1", "L2"]}
    kernels_done = 0
    kernels_skipped = 0

    for ki, (level, kf, problem_id, problem_dir, speedup, turn) in enumerate(all_kernels):
        kernel_key = f"{level}_P{problem_id}"

        if kernel_key in results["kernels"]:
            prev = results["kernels"][kernel_key]
            for s in statuses:
                cnt = prev.get(s, 0)
                grand[s] += cnt
                level_grand[level][s] += cnt
            for label, cnt in prev.get("per_op", {}).items():
                cat = label[0]
                for s in statuses:
                    cat_grand[cat][s] += cnt.get(s, 0)
            kernels_done += 1
            continue

        problem_file = find_problem_file(problem_dir, problem_id)
        if problem_file is None:
            P(f"  [{ki+1}/{len(all_kernels)}] SKIP {kernel_key} (no problem file)")
            kernels_skipped += 1
            continue

        if not kf.exists():
            P(f"  [{ki+1}/{len(all_kernels)}] SKIP {kernel_key} (kernel file missing: {kf})")
            kernels_skipped += 1
            continue

        gen_source = kf.read_text(encoding="utf-8", errors="replace")

        try:
            ref_mod = load_module(problem_file, f"prob_{level}_{problem_id}_{ki}")
            get_inputs = ref_mod.get_inputs
            get_init_inputs = ref_mod.get_init_inputs
        except Exception as e:
            P(f"  [{ki+1}/{len(all_kernels)}] SKIP {kernel_key} (ref: {str(e)[:60]})")
            kernels_skipped += 1
            continue

        P(f"  [{ki+1}/{len(all_kernels)}] {kernel_key} "
          f"(turn={turn}, speedup={speedup:.3f}, {len(gen_source)} bytes)")

        k_results = {s: 0 for s in statuses}
        k_per_op = {}

        for label, op in ALL_OPS:
            cat = label[0]
            try:
                sites = op.find_sites(gen_source)
            except Exception:
                P(f"    {label} -> find_sites error, skip")
                continue
            if not sites:
                continue

            sampled = random.sample(sites, min(SAMPLE_PER_OP, len(sites)))
            for si, site in enumerate(sampled):
                try:
                    mutated = op.apply(gen_source, site)
                except Exception:
                    continue

                mut_id = f"{level}_{problem_id}_{label}_{si}_{ki}"
                P(f"    {label} compiling...")
                t0 = time.time()
                result = classify(
                    gen_source, mutated, ref_mod,
                    get_inputs, get_init_inputs, tmp_dir, mut_id
                )
                elapsed = time.time() - t0

                k_results[result] += 1
                grand[result] += 1
                cat_grand[cat][result] += 1
                level_grand[level][result] += 1

                if label not in k_per_op:
                    k_per_op[label] = {s: 0 for s in statuses}
                k_per_op[label][result] += 1

                P(f"    {label} -> {result} ({elapsed:.0f}s)")

        k_killed = k_results["killed"]
        k_surv = k_results["survived"]
        k_nt = k_killed + k_surv
        kr = k_killed / max(1, k_nt)
        P(f"    >> {kernel_key}: killed={k_killed} surv={k_surv} "
          f"still={k_results['stillborn']} tmo={k_results['timeout']} KR={kr:.0%}")

        results["kernels"][kernel_key] = {
            **k_results,
            "per_op": k_per_op,
            "turn": turn,
            "speedup": speedup,
        }
        save_results(results)
        kernels_done += 1

        # Purge loaded mutant modules and GPU memory to prevent VRAM exhaustion
        stale = [k for k in sys.modules if k.startswith("mut_") or k.startswith("prob_")]
        for k in stale:
            del sys.modules[k]
        import gc; gc.collect()
        torch.cuda.empty_cache()

        elapsed_total = time.time() - total_time_start
        avg_per_kernel = elapsed_total / max(1, kernels_done)
        remaining = len(all_kernels) - ki - 1
        eta_min = remaining * avg_per_kernel / 60
        P(f"    [progress: {kernels_done}/{len(all_kernels)}, "
          f"elapsed={elapsed_total/60:.1f}min, ETA={eta_min:.0f}min]")

    total_elapsed = time.time() - total_time_start

    # ===== SUMMARY =====
    P(f"\n{'='*70}")
    P(f"  FULL KILL RATE SUMMARY (elapsed: {total_elapsed/60:.1f} min)")
    P(f"{'='*70}")
    P(f"  Kernels tested: {kernels_done}, skipped: {kernels_skipped}")

    P(f"\n  Per-Level:")
    P(f"  {'Level':<6} {'Kill':>6} {'Surv':>6} {'Still':>6} {'TMO':>5} {'Total':>6} {'KR':>7}")
    P(f"  {'-'*44}")
    for lv in ["L1", "L2"]:
        s = level_grand[lv]
        nt = s["killed"] + s["survived"]
        kr = s["killed"] / max(1, nt)
        total = sum(s.values())
        P(f"  {lv:<6} {s['killed']:>6} {s['survived']:>6} {s['stillborn']:>6} "
          f"{s['timeout']:>5} {total:>6} {kr:>6.1%}")

    P(f"\n  Per-Category:")
    P(f"  {'Cat':<6} {'Kill':>6} {'Surv':>6} {'Still':>6} {'TMO':>5} {'KR':>7}")
    P(f"  {'-'*38}")
    for cat in "ABCD":
        s = cat_grand[cat]
        nt = s["killed"] + s["survived"]
        kr = s["killed"] / max(1, nt)
        P(f"  {cat:<6} {s['killed']:>6} {s['survived']:>6} {s['stillborn']:>6} "
          f"{s['timeout']:>5} {kr:>6.1%}")

    killed_total = grand["killed"]
    total_nt = killed_total + grand["survived"]
    overall_kr = killed_total / max(1, total_nt)
    total_all = sum(grand.values())
    P(f"  {'-'*38}")
    P(f"  {'ALL':<6} {grand['killed']:>6} {grand['survived']:>6} {grand['stillborn']:>6} "
      f"{grand['timeout']:>5} {overall_kr:>6.1%}")

    P(f"\n  Overall Kill Rate: {overall_kr:.1%}")
    P(f"  Stillborn Rate: {grand['stillborn']/max(1,total_all):.1%}")
    P(f"  Total mutants: {total_all}")
    P(f"  Total time: {total_elapsed/60:.1f} min ({total_elapsed/3600:.1f} hours)")

    results["summary"] = {
        "overall_kill_rate": overall_kr,
        "total_mutants": total_all,
        "grand": grand,
        "cat_grand": cat_grand,
        "level_grand": level_grand,
        "elapsed_hours": total_elapsed / 3600,
        "kernels_tested": kernels_done,
        "kernels_skipped": kernels_skipped,
    }
    save_results(results)
    P(f"\n  Results saved to: {RESULT_FILE}")


if __name__ == "__main__":
    main()
